---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kong
  namespace: networking
spec:
  chart:
    spec:
      chart: kong
      sourceRef:
        kind: HelmRepository
        name: kong-charts
        namespace: flux-system
      interval: 5m
