apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  labels:
    app: plex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      containers:
        - name: plex
          image: linuxserver/plex
          imagePullPolicy: Always
          ports:
            - containerPort: 32400
              name: plex
          env:
            - name: PGID
              value: "17464003"
            - name: PUID
              value: "17464002"
            - name: TZ
              value: "America/New_York"
            - name: PLEX_CLAIM
              value: "claim-asdfasdfasdf"
          volumeMounts:
            - name: plex-config
              mountPath: /config
            - name: plex-media
              mountPath: /Media
      volumes:
        - name: plex-config
          nfs:
            server: 10.0.0.20
            path: /srv/K8s/plex-config
        - name: plex-media
          nfs:
            server: 10.0.0.20
            path: /srv/Media

---
kind: Service
apiVersion: v1
metadata:
  name: plex
spec:
  selector:
    app: plex
  ports:
    - name: plex
      protocol: TCP
      port: 32400
      targetPort: 32400
  type: NodePort
