---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pihole 
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      chart: pihole 
      sourceRef:
        kind: HelmRepository
        name: pihole-charts
        namespace: flux-system
      interval: 5m
  values:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "kong"
      hosts: ["pi.hole"]
      path: "/"
      tls: []
    persistentVolumeClaim:
      enabled: true
    serviceTCP:
      type: LoadBalancer
      annotations:
        metallb.universe.tf/address-pool: default
        metallb.universe.tf/allow-shared-ip: pihole-svc
    serviceUDP:
      type: LoadBalancer
      annotations:
        metallb.universe.tf/address-pool: default
        metallb.universe.tf/allow-shared-ip: pihole-svc
